stock_defconfig: Satisfy VINTF checks VINTF see mojito-stock_defconfig instead of mojito_defconfig‎
This fixes the following error:
ERROR: files are incompatible: Runtime info and framework compatibility matrix are incompatible: No compatible kernel requirement found (kernel FCM version = 6).
For kernel requirements at matrix level 6, Kernel config errors:
    Missing config CONFIG_HAVE_MOVE_PMD
    Missing config CONFIG_HAVE_MOVE_PUD
    Missing config CONFIG_USERFAULTFD
: Success
INCOMPATIBLE

Change-Id: I5354e368b7614586a3ee6c3fe2699e008f847cc8
Signed-off-by: angelomds42 <angelomds42@gmail.com>
Signed-off-by: romgharti <romgharti@gmail.com>